"""Infrastructure: settings, logging, callbacks, caching, costs, discovery."""

from .accounts import (
    AccountSnapshot,
    AccountSource,
    aget_account_snapshots,
    get_account_snapshot,
    get_account_snapshots,
    register_account_source,
    unregister_account_source,
)
from .billing import (
    BillingAPIError,
    BillingClient,
    BillingReport,
    BillingRow,
    BillingScope,
    CostReconciliation,
    LocalCostSummary,
    reconcile_costs,
)
from .budget import (
    BudgetPolicy,
    BudgetState,
    CostEstimate,
    enforce_budget,
    estimate_call_cost,
    estimate_cost,
    estimate_tokens,
    resolve_budget_policy,
)
from .cache import (
    CacheBackend,
    MemoryCacheBackend,
    RedisCacheBackend,
    ResponseCache,
    SQLiteCacheBackend,
    configure_cache,
    get_cache,
)
from .callbacks import DriverCallbacks
from .capabilities import (
    ProviderCapabilities,
    clear_overrides,
    get_capabilities,
    get_compatibility_matrix,
    override_capabilities,
    register_model,
    register_provider,
)
from .coding_agent_events import (
    CodingAgentEvent,
    detect_question,
    parse_claude_stream_json_lines,
    parse_codex_json_lines,
)
from .coding_agent_specs import (
    CODING_AGENT_SPECS,
    CodingAgentSpec,
)
from .coding_agent_specs import (
    get_spec as get_coding_agent_spec,
)
from .coding_agent_specs import (
    supported_agent_ids as supported_coding_agent_ids,
)
from .coding_agent_usage import (
    USAGE_READERS,
    AgentCall,
    CodingAgentUsage,
    UsageReader,
    coding_agents_overview,
    register_usage_reader,
)
from .coding_agents import (
    ApprovalMode,
    CodingAgentCommand,
    CodingAgentRunResult,
    arun_coding_agent,
    astream_coding_agent,
    build_coding_agent_command,
    run_coding_agent,
)
from .compression import CompressionStats, compress_messages
from .cost_mixin import AudioCostMixin, EmbeddingCostMixin, VideoCostMixin
from .discovery import (
    CodingAgentExecutable,
    CodingAgentInfo,
    clear_discovery_cache,
    display_available_models,
    get_available_audio_models,
    get_available_coding_agents,
    get_available_decision_models,
    get_available_embedding_models,
    get_available_image_gen_models,
    get_available_lipsync_models,
    get_available_models,
    get_available_moderation_models,
    get_available_music_models,
    get_available_rerank_models,
    get_available_video_gen_models,
    get_coding_agent_executable_candidates,
    pick_best_coding_agent,
    resolve_coding_agent_binary,
    resolve_coding_agent_executable,
    verify_coding_agent_binary,
    verify_coding_agent_executable,
)
from .ledger import ModelUsageLedger, get_recently_used_models
from .logging import JSONFormatter, configure_logging
from .model_rates import (
    ModelCapabilities,
    get_model_capabilities,
    get_model_info,
    get_model_lifecycle,
    get_model_rates,
    refresh_rates_cache,
)
from .otel import instrument_driver, otel_callbacks
from .provider_env import ProviderEnvironment
from .rate_limits import (
    LimitSnapshot,
    LimitWindow,
    add_rate_limits,
    capture_rate_limits,
    limits_from_response,
    parse_rate_limit_headers,
)

try:
    from .tukuy_backend import TukuyLLMBackend, create_tukuy_backend
except ImportError:  # tukuy not installed
    TukuyLLMBackend = None  # type: ignore[assignment,misc]
    create_tukuy_backend = None  # type: ignore[assignment]
from .session import UsageSession
from .settings import settings
from .token_counting import (
    TokenCount,
    acount_request_tokens,
    aestimate_request_cost,
    count_request_tokens,
    estimate_request_cost,
)
from .tracker import UsageEvent, UsageSink, UsageTracker, configure_tracker, get_tracker

__all__ = [
    "CODING_AGENT_SPECS",
    "USAGE_READERS",
    "AccountSnapshot",
    "AccountSource",
    "AgentCall",
    "ApprovalMode",
    "AudioCostMixin",
    "BillingAPIError",
    "BillingClient",
    "BillingReport",
    "BillingRow",
    "BillingScope",
    "BudgetPolicy",
    "BudgetState",
    "CacheBackend",
    "CodingAgentCommand",
    "CodingAgentEvent",
    "CodingAgentExecutable",
    "CodingAgentInfo",
    "CodingAgentRunResult",
    "CodingAgentSpec",
    "CodingAgentUsage",
    "CompressionStats",
    "CostEstimate",
    "CostReconciliation",
    "DriverCallbacks",
    "EmbeddingCostMixin",
    "JSONFormatter",
    "LimitSnapshot",
    "LimitWindow",
    "LocalCostSummary",
    "MemoryCacheBackend",
    "ModelCapabilities",
    "ModelUsageLedger",
    "ProviderCapabilities",
    "ProviderEnvironment",
    "RedisCacheBackend",
    "ResponseCache",
    "SQLiteCacheBackend",
    "TokenCount",
    "TukuyLLMBackend",
    "UsageEvent",
    "UsageReader",
    "UsageSession",
    "UsageSink",
    "UsageTracker",
    "VideoCostMixin",
    "acount_request_tokens",
    "add_rate_limits",
    "aestimate_request_cost",
    "aget_account_snapshots",
    "arun_coding_agent",
    "astream_coding_agent",
    "build_coding_agent_command",
    "capture_rate_limits",
    "clear_discovery_cache",
    "clear_overrides",
    "coding_agents_overview",
    "compress_messages",
    "configure_cache",
    "configure_logging",
    "configure_tracker",
    "count_request_tokens",
    "create_tukuy_backend",
    "detect_question",
    "display_available_models",
    "enforce_budget",
    "estimate_call_cost",
    "estimate_cost",
    "estimate_request_cost",
    "estimate_tokens",
    "get_account_snapshot",
    "get_account_snapshots",
    "get_available_audio_models",
    "get_available_coding_agents",
    "get_available_decision_models",
    "get_available_embedding_models",
    "get_available_image_gen_models",
    "get_available_lipsync_models",
    "get_available_models",
    "get_available_moderation_models",
    "get_available_music_models",
    "get_available_rerank_models",
    "get_available_video_gen_models",
    "get_cache",
    "get_capabilities",
    "get_coding_agent_executable_candidates",
    "get_coding_agent_spec",
    "get_compatibility_matrix",
    "get_model_capabilities",
    "get_model_info",
    "get_model_lifecycle",
    "get_model_rates",
    "get_recently_used_models",
    "get_tracker",
    "instrument_driver",
    "limits_from_response",
    "otel_callbacks",
    "override_capabilities",
    "parse_claude_stream_json_lines",
    "parse_codex_json_lines",
    "parse_rate_limit_headers",
    "pick_best_coding_agent",
    "reconcile_costs",
    "refresh_rates_cache",
    "register_account_source",
    "register_model",
    "register_provider",
    "register_usage_reader",
    "resolve_budget_policy",
    "resolve_coding_agent_binary",
    "resolve_coding_agent_executable",
    "run_coding_agent",
    "settings",
    "supported_coding_agent_ids",
    "unregister_account_source",
    "verify_coding_agent_binary",
    "verify_coding_agent_executable",
]
