"""Media handling: images, audio, and video."""

from .hosting import (
    FileHost,
    InMemoryHost,
    LocalDiskHost,
    S3PresignedHost,
    content_hash,
    default_host,
    host_media,
    resolve_to_bytes,
    save_media,
)
from .audio import (
    AudioContent,
    AudioInput,
    audio_from_base64,
    audio_from_bytes,
    audio_from_file,
    audio_from_url,
    make_audio,
)
from .image import (
    ImageContent,
    ImageInput,
    image_from_base64,
    image_from_bytes,
    image_from_file,
    image_from_url,
    make_image,
)
from .video import (
    VideoContent,
    VideoInput,
    make_video,
    video_from_base64,
    video_from_bytes,
    video_from_file,
    video_from_url,
)

__all__ = [
    "FileHost",
    "InMemoryHost",
    "LocalDiskHost",
    "S3PresignedHost",
    "content_hash",
    "default_host",
    "host_media",
    "resolve_to_bytes",
    "save_media",
    "AudioContent",
    "AudioInput",
    "ImageContent",
    "ImageInput",
    "VideoContent",
    "VideoInput",
    "audio_from_base64",
    "audio_from_bytes",
    "audio_from_file",
    "audio_from_url",
    "image_from_base64",
    "image_from_bytes",
    "image_from_file",
    "image_from_url",
    "make_audio",
    "make_image",
    "make_video",
    "video_from_base64",
    "video_from_bytes",
    "video_from_file",
    "video_from_url",
]
