"""LLM image-prompt enhancer — expand a terse brief into a vivid, structured prompt.

A pure text->text transform that rides any registered text/chat model through
the standard ``ask_for_json`` path; it never touches an image driver, so it is
uniform across every image provider. On any failure (no model, LLM error, empty
result) it returns the original prompt unchanged so it can never block
generation.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .style_presets import StylePreset

logger = logging.getLogger("prompture.imaging.enhance")

_ENHANCE_SYSTEM = (
    "You are an expert image-prompt engineer. Rewrite the user's brief into a "
    "single, vivid, well-structured image generation prompt. Cover subject, "
    "composition, lighting, color, mood, medium, and level of detail. Preserve "
    "the user's intent and any specific subjects, wording, or constraints they "
    "named. Do not invent brand names. Return only the rewritten prompt."
)

_ENHANCE_SCHEMA = {
    "type": "object",
    "properties": {"enhanced_prompt": {"type": "string"}},
    "required": ["enhanced_prompt"],
}


def _build_instruction(
    prompt: str,
    style: str | StylePreset | None,
    target_model: str | None,
    max_words: int,
) -> str:
    from .style_presets import StylePreset, get_style_preset

    lines = [f"Brief: {prompt}"]

    preset: StylePreset | None = None
    if isinstance(style, StylePreset):
        preset = style
    elif isinstance(style, str):
        preset = get_style_preset(style)
    if preset is not None:
        guidance = preset.description or ""
        if preset.prompt_suffix:
            guidance = f"{guidance} ({preset.prompt_suffix})".strip()
        lines.append(f"Target style: {preset.label} — {guidance}".rstrip(" —"))

    if target_model:
        lines.append(f"The image will be generated by '{target_model}'.")
    lines.append(f"Keep the rewritten prompt under {max_words} words.")
    return "\n".join(lines)


def _read_enhanced(result: dict[str, Any], fallback: str) -> str:
    enhanced = ((result.get("json_object") or {}).get("enhanced_prompt") or "").strip()
    return enhanced or fallback


def enhance_image_prompt(
    prompt: str,
    *,
    model: str | None = None,
    driver: Any | None = None,
    style: str | StylePreset | None = None,
    target_model: str | None = None,
    max_words: int = 120,
    env: Any | None = None,
    options: dict[str, Any] | None = None,
) -> str:
    """Expand ``prompt`` into a richer image prompt using a text model.

    Provide either ``model`` (e.g. ``"openai/gpt-4o-mini"``) or a ready
    ``driver``. ``style`` accepts a :class:`StylePreset` or a registered preset
    id to bias the rewrite. Returns the original prompt on any failure.
    """
    from ..agents.conversation import Conversation

    if not (prompt and prompt.strip()):
        return prompt
    try:
        conv = Conversation(model_name=model, driver=driver, system_prompt=_ENHANCE_SYSTEM, env=env)
        result = conv.ask_for_json(
            _build_instruction(prompt, style, target_model, max_words),
            _ENHANCE_SCHEMA,
            options=options,
        )
        return _read_enhanced(result, prompt)
    except Exception:
        logger.warning("Prompt enhancement failed; returning the original prompt.", exc_info=True)
        return prompt


async def aenhance_image_prompt(
    prompt: str,
    *,
    model: str | None = None,
    driver: Any | None = None,
    style: str | StylePreset | None = None,
    target_model: str | None = None,
    max_words: int = 120,
    env: Any | None = None,
    options: dict[str, Any] | None = None,
) -> str:
    """Async twin of :func:`enhance_image_prompt`."""
    from ..agents.async_conversation import AsyncConversation

    if not (prompt and prompt.strip()):
        return prompt
    try:
        conv = AsyncConversation(model_name=model, driver=driver, system_prompt=_ENHANCE_SYSTEM, env=env)
        result = await conv.ask_for_json(
            _build_instruction(prompt, style, target_model, max_words),
            _ENHANCE_SCHEMA,
            options=options,
        )
        return _read_enhanced(result, prompt)
    except Exception:
        logger.warning("Async prompt enhancement failed; returning the original prompt.", exc_info=True)
        return prompt
