"""LLM image-prompt enhancer — expand a terse brief into a vivid, structured prompt.

A pure text->text transform that rides any registered text/chat model through
the standard ``ask_for_json`` path; it never touches an image driver, so it is
uniform across every image provider. On any failure (no model, LLM error, empty
result) it returns the original prompt unchanged so it can never block
generation.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .style_presets import StylePreset

logger = logging.getLogger("prompture.imaging.enhance")

_ENHANCE_SYSTEM = (
    "You are an expert image-prompt engineer. Rewrite the user's brief into a "
    "single, vivid, well-structured image generation prompt. Cover subject, "
    "composition, lighting, color, mood, medium, and level of detail. Preserve "
    "the user's intent and any specific subjects, wording, or constraints they "
    "named. Do not invent brand names. Return only the rewritten prompt."
)

_ENHANCE_SCHEMA = {
    "type": "object",
    "properties": {"enhanced_prompt": {"type": "string"}},
    "required": ["enhanced_prompt"],
}


@dataclass(frozen=True)
class EnhancedPrompt:
    """The enhancer's full result — the rewrite plus what it cost.

    :func:`enhance_image_prompt` returns a bare ``str`` and always will; this
    is for callers that also need the token/cost summary (``usage``, in the
    shape ``ask_for_json`` returns). ``changed`` is ``False`` when the rewrite
    fell back to the original — no model, an LLM error, or an empty result —
    in which case ``usage`` is empty.
    """

    prompt: str
    original: str
    model: str | None = None
    usage: dict[str, Any] = field(default_factory=dict)

    @property
    def changed(self) -> bool:
        return self.prompt != self.original

    def __str__(self) -> str:
        return self.prompt


def _build_instruction(
    prompt: str,
    style: str | StylePreset | None,
    target_model: str | None,
    max_words: int,
) -> str:
    from .style_presets import StylePreset, get_style_preset

    lines = [f"Brief: {prompt}"]

    preset: StylePreset | None = None
    if isinstance(style, StylePreset):
        preset = style
    elif isinstance(style, str):
        preset = get_style_preset(style)
    if preset is not None:
        guidance = preset.description or ""
        if preset.prompt_suffix:
            guidance = f"{guidance} ({preset.prompt_suffix})".strip()
        lines.append(f"Target style: {preset.label} — {guidance}".rstrip(" —"))

    if target_model:
        lines.append(f"The image will be generated by '{target_model}'.")
    lines.append(f"Keep the rewritten prompt under {max_words} words.")
    return "\n".join(lines)


def _read_enhanced(result: dict[str, Any], fallback: str) -> str:
    enhanced = ((result.get("json_object") or {}).get("enhanced_prompt") or "").strip()
    return enhanced or fallback


def enhance_image_prompt_detailed(
    prompt: str,
    *,
    model: str | None = None,
    driver: Any | None = None,
    style: str | StylePreset | None = None,
    target_model: str | None = None,
    max_words: int = 120,
    env: Any | None = None,
    options: dict[str, Any] | None = None,
) -> EnhancedPrompt:
    """Expand ``prompt`` and report what the rewrite cost.

    Same behaviour as :func:`enhance_image_prompt` — it is this function's
    ``.prompt`` — but returns an :class:`EnhancedPrompt` carrying ``usage``.
    Never raises: every failure path falls back to the original prompt with
    empty usage.
    """
    from ..agents.conversation import Conversation

    if not (prompt and prompt.strip()):
        return EnhancedPrompt(prompt=prompt, original=prompt, model=model)
    try:
        conv = Conversation(model_name=model, driver=driver, system_prompt=_ENHANCE_SYSTEM, env=env)
        result = conv.ask_for_json(
            _build_instruction(prompt, style, target_model, max_words),
            _ENHANCE_SCHEMA,
            options=options,
        )
        return EnhancedPrompt(
            prompt=_read_enhanced(result, prompt),
            original=prompt,
            model=model,
            # Billed even when the model returned nothing usable, so usage is
            # reported on the empty-result path too — only the no-call and
            # exception paths leave it empty.
            usage=dict(result.get("usage") or {}),
        )
    except Exception:
        logger.warning("Prompt enhancement failed; returning the original prompt.", exc_info=True)
        return EnhancedPrompt(prompt=prompt, original=prompt, model=model)


async def aenhance_image_prompt_detailed(
    prompt: str,
    *,
    model: str | None = None,
    driver: Any | None = None,
    style: str | StylePreset | None = None,
    target_model: str | None = None,
    max_words: int = 120,
    env: Any | None = None,
    options: dict[str, Any] | None = None,
) -> EnhancedPrompt:
    """Async twin of :func:`enhance_image_prompt_detailed`."""
    from ..agents.async_conversation import AsyncConversation

    if not (prompt and prompt.strip()):
        return EnhancedPrompt(prompt=prompt, original=prompt, model=model)
    try:
        conv = AsyncConversation(model_name=model, driver=driver, system_prompt=_ENHANCE_SYSTEM, env=env)
        result = await conv.ask_for_json(
            _build_instruction(prompt, style, target_model, max_words),
            _ENHANCE_SCHEMA,
            options=options,
        )
        return EnhancedPrompt(
            prompt=_read_enhanced(result, prompt),
            original=prompt,
            model=model,
            usage=dict(result.get("usage") or {}),
        )
    except Exception:
        logger.warning("Async prompt enhancement failed; returning the original prompt.", exc_info=True)
        return EnhancedPrompt(prompt=prompt, original=prompt, model=model)


def enhance_image_prompt(
    prompt: str,
    *,
    model: str | None = None,
    driver: Any | None = None,
    style: str | StylePreset | None = None,
    target_model: str | None = None,
    max_words: int = 120,
    env: Any | None = None,
    options: dict[str, Any] | None = None,
) -> str:
    """Expand ``prompt`` into a richer image prompt using a text model.

    Provide either ``model`` (e.g. ``"openai/gpt-4o-mini"``) or a ready
    ``driver``. ``style`` accepts a :class:`StylePreset` or a registered preset
    id to bias the rewrite. Returns the original prompt on any failure.

    Use :func:`enhance_image_prompt_detailed` when you also need the call's
    token/cost usage.
    """
    return enhance_image_prompt_detailed(
        prompt,
        model=model,
        driver=driver,
        style=style,
        target_model=target_model,
        max_words=max_words,
        env=env,
        options=options,
    ).prompt


async def aenhance_image_prompt(
    prompt: str,
    *,
    model: str | None = None,
    driver: Any | None = None,
    style: str | StylePreset | None = None,
    target_model: str | None = None,
    max_words: int = 120,
    env: Any | None = None,
    options: dict[str, Any] | None = None,
) -> str:
    """Async twin of :func:`enhance_image_prompt`."""
    result = await aenhance_image_prompt_detailed(
        prompt,
        model=model,
        driver=driver,
        style=style,
        target_model=target_model,
        max_words=max_words,
        env=env,
        options=options,
    )
    return result.prompt
