"""Core extraction engine: schema-enforced JSON extraction from LLMs."""

from .core import (
    Driver,
    ask_for_json,
    clean_json_text_with_ai,
    extract_and_jsonify,
    extract_from_data,
    extract_from_pandas,
    extract_with_model,
    manual_extract_and_jsonify,
    render_output,
    stepwise_extract_with_model,
)
from .fields import (
    FIELD_DEFINITIONS,
    add_field_definition,
    add_field_definitions,
    clear_registry,
    field_from_registry,
    get_field_definition,
    get_field_names,
    get_registry_snapshot,
    get_required_fields,
    normalize_enum_value,
    register_field,
    reset_registry,
    validate_enum_value,
)
from .reasoning import (
    PLAN_AND_SOLVE,
    SELF_DISCOVER,
    ReasoningStrategy,
    ReasoningStrategyProtocol,
    apply_reasoning_strategy,
    auto_select_reasoning_strategy,
    get_reasoning_strategy,
    list_reasoning_strategies,
    register_reasoning_strategy,
    reset_reasoning_strategy_registry,
    unregister_reasoning_strategy,
)
from .tools import clean_json_text, clean_toon_text
from .validator import validate_against_schema

__all__ = [
    "FIELD_DEFINITIONS",
    "PLAN_AND_SOLVE",
    "SELF_DISCOVER",
    "Driver",
    "ReasoningStrategy",
    "ReasoningStrategyProtocol",
    "add_field_definition",
    "add_field_definitions",
    "apply_reasoning_strategy",
    "ask_for_json",
    "auto_select_reasoning_strategy",
    "clean_json_text",
    "clean_json_text_with_ai",
    "clean_toon_text",
    "clear_registry",
    "extract_and_jsonify",
    "extract_from_data",
    "extract_from_pandas",
    "extract_with_model",
    "field_from_registry",
    "get_field_definition",
    "get_field_names",
    "get_reasoning_strategy",
    "get_registry_snapshot",
    "get_required_fields",
    "list_reasoning_strategies",
    "manual_extract_and_jsonify",
    "normalize_enum_value",
    "register_field",
    "register_reasoning_strategy",
    "render_output",
    "reset_reasoning_strategy_registry",
    "reset_registry",
    "stepwise_extract_with_model",
    "unregister_reasoning_strategy",
    "validate_against_schema",
    "validate_enum_value",
]
